### ISSUE TITLE
INFOGRAFÍA: CICLO DE VIDA DE UN SISTEMA

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-1-infografia-yanet-02#2]
[Infografìa-CICLO DE VIDA DE UN SISTEMAYanetGonzalez.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-yanet-02/files/12487336/Infografia-CICLO.DE.VIDA.DE.UN.SISTEMAYanetGonzalez.pdf)

**Comment by saul19bautista** [comment]
Buen trabajo 18.8/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
